### ISSUE TITLE
Crear un install.sh

### ISSUE THREAD

**Issue by dtisoy** [elliotsecops/System-Monitor#2]
Al descargar el repo, se podria usar un script install.sh para colocar el archivo system_monitor.sh en la ruta ~/.local/bin y así esté disponible el comando en cualquier parte.

Ya que el script system_monitor.sh tiene el shebang, se puede quitar la extencion .sh. Quedaría algo asi: 
![image](https://github.com/user-attachments/assets/616c7885-b1ed-411a-ad88-55b8f7239dbf)
_en la ultima columna se puede ver que el comando está disponible_

**Comment by elliotsecops** [comment]
¡Gracias por la sugerencia! He implementado un script `install.sh` para hacer que el script `system_monitor` esté disponible en todo el sistema. Este script copiará el script `system_monitor.sh` a `~/.local/bin/system_monitor` y lo hará ejecutable.

1. **Hacer que el Script Sea Ejecutable**

   ```bash
   chmod +x system_monitor.sh
   ```

3. **Ejecutar el Script de Instalación**

Después de la instalación, puedes ejecutar el comando `system_monitor` desde cualquier directorio:

### Notas Adicionales

- **Variables de Entorno**: Asegúrate de que `~/.local/bin` esté en tu variable de entorno `PATH`. Puedes agregar la siguiente línea a tu archivo `~/.bashrc` o `~/.zshrc` si no está allí:


- **Script de Desinstalación**: También he creado un script `uninstall.sh` para eliminar el script del sistema:


### README Actualizado

He actualizado el archivo `README.md` con instrucciones detalladas sobre cómo instalar, configurar y utilizar el script `system_monitor`. Puedes encontrar el `README.md` actualizado en el repositorio.

Si tienes más sugerencias o encuentras algún problema, por favor, házmelo saber.
¡Gracias por tu contribución!
